---
linters:
  enable:
    - contextcheck
    - cyclop
    - gocritic
    - goimports
    - gosec
    - paralleltest
    - promlinter
    - revive
    - testifylint
    - thelper
    - unparam
    - whitespace

linters-settings:
  gocritic:
    enabled-checks:
      - appendCombine
      - emptyStringTest
      - importShadow
      - octalLiteral
      - rangeValCopy

  gosec:
    excludes:
      - G114

  revive:
    rules:
      - name: if-return
        disabled: false
      - name: import-alias-naming
        disabled: false

run:
  timeout: 5m
