version: "2"
linters:
  enable:
    - contextcheck
    - cyclop
    - gocritic
    - gosec
    - paralleltest
    - promlinter
    - revive
    - testifylint
    - thelper
    - unparam
    - whitespace
  settings:
    cyclop:
      max-complexity: 15
    gocritic:
      enabled-checks:
        - appendCombine
        - emptyStringTest
        - importShadow
        - octalLiteral
        - rangeValCopy
    gosec:
      excludes:
        - G114
    revive:
      rules:
        - name: if-return
          disabled: false
        - name: import-alias-naming
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

run:
  timeout: 5m
