name: Tag

on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      upload_artifacts: true
    permissions:
      contents: read
      pull-requests: read
      checks: write

  release:
    permissions:
      contents: write
    needs:
      - build
    uses: ./.github/workflows/release.yml
